### ISSUE TITLE
I want to add the feature to add a field with prefix-sequenceNo-suffix as string while generating the sequence Number

### ISSUE THREAD

**Issue by KaranSantra** [ramiel/mongoose-sequence#102]
I wanted to add a string field that is created along with the sequence number, the string field can have a prefix and/or a suffix string as well.
Example:
```
//input options
prefix = "DEV-"
//record created
{ "name":"ramiel", seqNo:123, sequenceString: "DEV-123"}
```

P.S I am new to open source so let me know if I am doing something wrong.

**Comment by KaranSantra** [comment]
Should I create a pr?

**Comment by ramiel** [comment]
At a first sight this doesn't seem to belong to this plugin. If you need this information at application level I think you can use a [`virtual` field](https://mongoosejs.com/docs/guide.html#virtuals). If you need this information saved on database you can use a `postSave` hook. Am I missing something?

**Comment by RanyHajYahia** [comment]
Looking for the same..
Currently we can use AutoIncrement as numbers where we can set a field to (1, 2, 3..).
As Karan mentioned maybe it will be a good idea to add 'prefix' and 'suffix' to options.
Example:
UserSchema.plugin(AutoIncrement, { inc_field: '_id', prefix: 'User_' });
Then _id will increment as a string with values ('User_1', 'User_2', ..) for each new document.

**Comment by ramiel** [comment]
As I said before, you should try to use a virtual field in mongoose, or a post save hook. They will solve your problem while the DB still contain the number. I would add it as a feature if it wasn't available, but virtual fields are there for these use cases. I'll reopen if there is any evidence this is not doable with current tools.
