### ISSUE TITLE
Question - Modern 'import' syntax

### ISSUE THREAD

**Issue by thomasthebro1** [ramiel/mongoose-sequence#111]
How do you use this module with the modern `import` syntax using TypeScript >=v4?
The reason why I am asking this is because you can't pass parameters (e.g. the database connection) to the `import` syntax

**Comment by ramiel** [comment]
You're right. This is the way to go

```ts
import AutoIncrementFactory  from 'mongoose-sequence';

const AutoIncrement = AutoIncrementFactory(mongoose);
```

Let me know if this works. Depending on your typescript setup you may need to adjust this code.

**Comment by thomasthebro1** [comment]
I think an adjustment maybe required. After implementing the code you told me to use TypeScript throws an error like the example demonstrated below when trying to pass `mongoose` to `SequenceFactory`. If this is my fault, please bare with me I am slowly migrating from CommonJS to TypeScript

`Argument of type * is not assignable to parameter of type *`

![image](https://user-images.githubusercontent.com/43547293/121699641-08362180-cac7-11eb-9ea0-dad6dd948872.png)

**Comment by ramiel** [comment]
Since this library is not type I don't know what typescript is inferring. Probably you should enforce `any`, something like

```ts
const Sequence = SequenceFactory(mongoose as any);
```
I'm sure what the factory expects is not a Schema<...>

**Comment by thomasthebro1** [comment]
Just tried this now and it seems to work however ESLint is now complaining. When specifying the type as `any` now ESLint prompts you with this message: `Unexpected any. Specify a different type.`
Is it possible that there might be a conflict with `@types/mongoose-sequence`?
![image](https://user-images.githubusercontent.com/43547293/121726394-658b9c00-cae2-11eb-9148-b64ede79e711.png)

**Comment by ramiel** [comment]
So '@types/mongoose-sequence' are the types for another package, not for this one. I never created the types

**Comment by thomasthebro1** [comment]
Oh that's strange! NPM [says otherwise](https://www.npmjs.com/package/@types/mongoose-sequence) and links me to install the types so that the package is compatible with TypeScript. Do you have any plans to integrate types into the package in the future?

I reckon that there might be some conflicts going on between `mongoose-sequence` and the types. The version(s) of the types and package don't really make total sense either so I guess that they might be behind and haven't been updated in a while...
![image](https://user-images.githubusercontent.com/43547293/121756035-c16d1980-cb10-11eb-8b8c-c53954515f6d.png)

**Comment by thomasthebro1** [comment]
When you don't have the declaration file for the types, TypeScript also begins to complain when the types don't exist after I've uninstalled them - `Could not find declaration file for module mongoose-sequence. Try npm i --save-dev @types/mongoose-sequence`

**Comment by ramiel** [comment]
Ok,first let me close this issue because now it's about your problem with typescript. In typescript you can declare a module without declaring its types. Please refer to typescript documentation to know how to handle modules that have no typings.

Here an example https://sodocumentation.net/typescript/topic/8249/how-to-use-a-javascript-library-without-a-type-definition-file#use-an-ambient-module

**Comment by ramiel** [comment]
The definition you pointed out has been written by someone else as you can see in the npm page. It's clearly for an old version. When typescript suggests a definition package it does only based on the name convention, regardless of the fact that the definition is correct or even if it exists.

**Comment by cityvoice** [comment]
@thomasthebro1 hi, have you resolved this bug? I also installed @types/mongoose-sequence according NPM's hint. And it doesn't work. It seems the latest @types/mongoose-sequence is for mongoose-sequence@3.0.2. I have contacted the author, but have no feedback still now. I have modified @types/mongoose-sequence myself. It works for me now.

```
declare module 'mongoose-sequence' {
  import mongoose = require('mongoose');
  var _: (connection: mongoose.Schema, options?: Object) => void;
  export = _;
}
```
changed to 

```
declare module 'mongoose-sequence' {
  import mongoose = require('mongoose');
  var _: (connection: mongoose.Connection) => PluginFunction;
  export = _;
}
```

**Comment by ramiel** [comment]
Hello @cityvoice . I'm not really active anymore in this project, ut if you would like to include the type definition directly in this package, I'll be happy to accept a PR.

**Comment by cityvoice** [comment]
Hi, ramiel.
I’m very sorry to bother you, I have resolved this problem, have a nice day!

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Fabrizio ***@***.***>
发送时间: 2023年2月8日 16:43
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ramiel/mongoose-sequence] Question - Modern 'import' syntax (#111)


Hello @cityvoice<https://github.com/cityvoice> . I'm not really active anymore in this project, ut if you would like to include the type definition directly in this package, I'll be happy to accept a PR.

―
