### ISSUE TITLE
Remove DeprecationWarning

### ISSUE THREAD

**Issue by anhdiepmmk** [ramiel/mongoose-sequence#113]
(node:27860) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#findandmodify

**Comment by ramiel** [comment]
This is up to you to set 

```
mongoose.set('useFindAndModify', false);
```

or

```
mongoose.connect(uri, { useFindAndModify: false });
```

on mongoose instance
