### ISSUE TITLE
set auto increment for more than one schema 

### ISSUE THREAD

**Issue by hezhaXoshnaw** [ramiel/mongoose-sequence#119]
hello,
when i set auto increment for 2 schema it gives me this error
throw new Error(`Counter already defined for field "${id}"`);

this is one of the schemas 
import * as mongoose from "mongoose";
const AutoIncrement = require('mongoose-sequence')(mongoose);

const studentSchema = new mongoose.Schema({
  _id: {
    type: Number,

  },
  name: {
    type: String,
    required: true,
    trim: true,
  }
},{_id : false});
studentSchema.plugin(AutoIncrement);

if i only set for this schema it will work without problem 
but if i set another schema the error occur

**Comment by ramiel** [comment]
You have to specify an 'id' for each counter separately. See
https://github.com/ramiel/mongoose-sequence#options

Il dom 6 feb 2022, 20:45 hezhaXoshnaw ***@***.***> ha scritto:

**Comment by hezhaXoshnaw** [comment]
thank you very much i didnt read the document clearly i found it and put for both sorry about that 

thanks for ur fast reply
