### ISSUE TITLE
Reset Counter

### ISSUE THREAD

**Issue by diego77777** [ramiel/mongoose-sequence#13]
Hello, 

is there a way to reset the counter? I did some inserts for test and now it would be nice to reset the counter.

thanks!

**Comment by ramiel** [comment]
No there is not, but is a good idea. Have you already an idea of how the api should look like?

**Comment by diego77777** [comment]
What about something like

bookSchema.plugin(autoIncrement.plugin, {
    id: 'rank_counter',
    startAt: 0,
    incrementBy: 1
});


?

**Comment by ramiel** [comment]
I was thinking more to some explicit action like

```js
BookModel.counterReset('counter_id')
```

**Comment by ramiel** [comment]
But I'm still not sure this is really useful. Maybe is only dangerous and the only way to do it shouldbe to remove the collection manually as an administration operation...

**Comment by ramiel** [comment]
It's available in version 3.2.0
