### ISSUE TITLE
does not work with mongoose 7

### ISSUE THREAD

**Issue by arnoldmq** [ramiel/mongoose-sequence#133]
it does not work with mongoose 7. Schema.create hangs. seems to be related to callbacks being deprecated.

**Comment by garryshield** [comment]
Me too,after upgrade to mongoose@7.0.0

**Comment by garryshield** [comment]
after some debug. mongoose@7.0.0 drop the callback supports for lots of model functions include `findOneAndUpdate`

[[Dropped callback support](https://mongoosejs.com/docs/migrating_to_7.html#dropped-callback-support)](https://mongoosejs.com/docs/migrating_to_7.html#dropped-callback-support)

[[this._counterModel.findOneAndUpdate(](https://github.com/ramiel/mongoose-sequence/blob/a5fbab316bc0089b1da9e6cdba1e92994cc42a73/lib/sequence.js#L341)](https://github.com/ramiel/mongoose-sequence/blob/a5fbab316bc0089b1da9e6cdba1e92994cc42a73/lib/sequence.js#L341)

maybe it's time to find another solution.

**Comment by Atitlanio** [comment]
why are you surprised people still use mongoose, is there a better solution for mongodb?

**Comment by edwardanthony** [comment]
@ramiel what about MongoDB itself? Are you dropping it as well?
Coming from SQL world, I'm also surprised that lookup performance on MongoDB is much worse compared to SQL.

**Comment by amansingh63** [comment]
> Hello everybody. Look, I have no more time to maintain this old library. Sometimes I'm also still impressed anybody keep using mongoose at all, but this is a free world ;) If anybody wants to take over is very welcome and I'm available to review PRs. For the moment I haver no time, no will to work on this library.

@ramiel i had opened a PR for mongoose v7 migration please have a look, Thanks.
https://github.com/ramiel/mongoose-sequence/pull/136

**Comment by Kozachokx** [comment]
Currently, the latest version of mongoose that works well is: [6.11.2](https://www.npmjs.com/package/mongoose/v/6.11.2)
`npm i mongoose@6.11.2`

**Comment by KiranCNayak** [comment]
> Currently, the latest version of mongoose that works well is: [6.11.2](https://www.npmjs.com/package/mongoose/v/6.11.2) `npm i mongoose@6.11.2`

I put crazy amounts of `console.log` statements to see where I'm going wrong. You saved me another hour or two. Now it is working in `6.11.2`. Thanks!

**Comment by ramiel** [comment]
Version 6.0.0 released with the changes from #136 and now latest version of mongoose is supported
