### ISSUE TITLE
How can i increment as a  string 

### ISSUE THREAD

**Issue by emirhanyagci** [ramiel/mongoose-sequence#141]
i have query like below, the chatPackId is auto incremented field and i can't use like that , chatPackId should be string how can i do that?

```js
{
    $or: [
      { username: { $regex: search, $options: "i" } },
      { email: { $regex: search, $options: "i" } },
      { chatPackId: { $regex: search } },
    ],
}
```

**Comment by ramiel** [comment]
From the documentation

> The only constraint is that the field has to be of type `Number`, otherwise the plugin will raise an error.

So, it must be a number
