### ISSUE TITLE
How do i change the id of the sequence?

### ISSUE THREAD

**Issue by joetidee** [ramiel/mongoose-sequence#17]
I want to change te id of the sequence to something that is more appropriate - how do I do this without resetting the counter?

Also, if migrating from my own previous sequence to using your package, how do I set the sequence to carry on from where it left off?

**Comment by ramiel** [comment]
You have to manually change the ID on the DB. There is collection named `counter`. Look for the document with the old `id` value and change it to the new.

For your second task there is not an easy way. I have on my todo-list to implement an option to set the starting value. Until that I think you have to modify the counter manually similarly as for the id.

let me know if everything worked
