### ISSUE TITLE
Don't working with Mongoose version upper than 4.7.9

### ISSUE THREAD

**Issue by sergey-zero** [ramiel/mongoose-sequence#18]
Don't working with Mongoose version upper than 4.7.9
Nodejs v7.7.3

**Comment by ramiel** [comment]
I have test passing with version 4.9.6    
Please, can you provide some more information? What's the error exactly? How can I reproduce it?

**Comment by sergey-zero** [comment]
https://github.com/sergey-zero/example
objects don't have order_id field with 4.9.7 version of mongoose, but working fine on 4.7.9
maby i'm do something wrong
`[ { _id: 5909717b8f1fde1b4f25e563, test: 'first', __v: 0 },
  { _id: 590971f2f68e0e1bd036f5ce, test: '1aa55', __v: 0 },
  { _id: 590971f7855a5a1bde32d665, test: '13352', __v: 0 },
  { _id: 590973225934721d6f69125a, test: '111ce', __v: 0 } ]`

**Comment by ramiel** [comment]
I'll have a look soon.

**Comment by ramiel** [comment]
Starting from `mongoose>4.7.9` looks like it's not possible anymore to change the schema after the model definition (see Automattic/mongoose#5203). This is true for plugins too, so if in your code you define the plugin before the model

```js
const testSchema = new mongoose.Schema({
    test: String,
    order_id: Number
});
// The plugin
testSchema.plugin(sequence, {inc_field: 'order_id'});
// And then the model
const Test = mongoose.model('Test',testSchema);
```
it should work. Let me know

**Comment by sergey-zero** [comment]
Wow, you are GOD, it's really works. Thank you so much!!
