### ISSUE TITLE
No response / hangs on Model.save (counter collection not created)

### ISSUE THREAD

**Issue by EnKrypt** [ramiel/mongoose-sequence#19]
For eg: I have a schema names `PostSchema`. If I remove the following line, everything works just fine:

```
PostSchema.plugin(AutoIncrement, {inc_field: 'id'});
```

However, if I keep the above line, whenever I create a new PostSchema object and call it's `save` method, the callback is never called and since I am using this via a webserver, nothing is sent back to the request. I have also tried setting the plugin for the `_id` field by following relevant instructions on the README, but experienced the same problem.

Note that the `counters` collection was never created during this entire process. Shouldn't the plugin have done so? (Might be of interest while debugging)

**Comment by ramiel** [comment]
Can you please post the code from the schema to the model creation to recreate the issue?Can you also write the version of the plugin?

**Comment by EnKrypt** [comment]
I don't *think* it's something I'm doing since I've kept my logic abstracted away from the plugin as much as possible, but if you find that I'm doing something silly, do let me know.  
For the same reason, there might be a decent amount of unnecessary stuff in the code below, but I've tried to cut it down to the relevant bits.

Code for schema (from when I tried setting the `_id` field to autoincrement) :
```
var PostSchema = mongoose.Schema({
    _id: Number,
    created: { type: Date, default: Date.now },
    updated: {
        flag: { type: Boolean, default: false },
        when: { type: Date, default: Date.now }
    },
    title: String,
    content: String,
    tags: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Tag', index: true }]
}, { _id: false });
PostSchema.plugin(AutoIncrement); // comes from the require() call to mongoose-sequence
app.db.model('Post', PostSchema);
```

Code for saving data to this model :
```
var newpost = new Post({
    created: new Date(),
    title: req.body.title,
    content: req.body.content,
    tags: tags.map(function (tag) {
        return tag._id;
    })
});
newpost.save(function (err, post) {
    console.log('A OK'); //Never executes
    if (err) {
        return handleError(req, res, err); //Never executes either
    }
    res.status(200).send({
        success: true
    });
});
```

Version of mongoose-sequence: 3.2.0
Version of mongoose: 4.9.8
Version of mongodb: 3.2.12

**Comment by ramiel** [comment]
I see nothing wrong in your code except for the line
```js
app.db.model('Post', PostSchema);
```
I guess `app.db` is `mongoose`.
The relative test on the repo (`increment _id if no field is specified`) is passing. So, I'm not able to reproduce the error, I'm sorry. Are you sure there is nothing else in your code which prevent this to work? Can you clone this repository and launch the test? Can you isolate more your code and launch it alone, something like this?
```js
var mongoose = require('mongoose');
var AutoIncrement = require('mongoose-sequence');

var PostSchema = mongoose.Schema({
    _id: Number,
    created: { type: Date, default: Date.now },
    updated: {
        flag: { type: Boolean, default: false },
        when: { type: Date, default: Date.now }
    },
    title: String,
    content: String,
    tags: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Tag', index: true }]
}, { _id: false });
PostSchema.plugin(AutoIncrement); 
mongoose.model('Post', PostSchema);
var newpost = new Post({
    created: new Date()
});
newpost.save(function (err, post) {
    console.log('save callback');
    console.log(err);
});
```

and launch this file only.

**Comment by EnKrypt** [comment]
> I guess app.db is mongoose.

Well technically it's the mongoose connection object, but alright. I personally can't think of anything I've written that might hinder this from working properly.

I've used my own workaround for the time being so I'm not sure when I'll revisit this package. 

If someone from the future with the same problem is reading this and I haven't followed up on the test above, I'd recommend them to continue on my behalf and/or reopen this issue if closed.
