### ISSUE TITLE
Multiple increment field

### ISSUE THREAD

**Issue by bokzor** [ramiel/mongoose-sequence#2]
Is it possible to use this plugin on several fields ?

Because the documentation said It's possible, but there is not example to achieve that.

Thanks for any help

**Comment by ramiel** [comment]
Yes is possible, simply recall the plugin several times for different fields. Here an example:

```js
UserSchema = mongoose.Schema({
    name: String,
    like: Number,
    visits: Number
});

UserSchema.plugin(AutoIncrement, {id: 'like_counter', inc_field: 'like', disable_hooks: true});
UserSchema.plugin(AutoIncrement, {id: 'visits_counter',inc_field: 'visits'});
```

Maybe in a future will be possible to do it in a single call but for now this is the way.

**Comment by bokzor** [comment]
I tried that way but the wrong field is used.

Let's admit we initialize that way : 

```
InvoiceSchema.plugin(AutoIncrement, {id: 'invoice_in', inc_field: 'invoiceIn', disable_hooks: true});
InvoiceSchema.plugin(AutoIncrement, {id: 'invoice_out', inc_field: 'invoiceOut', disable_hooks: true});
```

If I use this method, It's the field InvoiceOut that is incremented ... :-/

```
invoice.setNext('invoice_in', function(err, invoice){
  invoice.save();
});
```

**Comment by ramiel** [comment]
Ok, give me time to check it ok?I'll be back to you soon

**Comment by ramiel** [comment]
There was a bug. Now I created a test. Can you please check the version on develop?
I'll publish the new version lately in any case.

**Comment by ramiel** [comment]
I also noticed that the "setNext" method do not save the document which is maybe the desired behavior. I'll implement an option for this or I'll accept any PR :)

**Comment by bokzor** [comment]
Great ! Thanks for your rapidity. I'm going to look at It

**Comment by ramiel** [comment]
Version 3.0.1 is published and should solve this problem.
Another change is that now when you call setNext the document is already saved so you don't need to save it manually anymore. In your example
```js
invoice.setNext('invoice_in', function(err, invoice){
    // The next line must be removed because invoice is already saved
    // invoice.save();
});
```

In a next version this will be an option.
