### ISSUE TITLE
is it possible to make a populate?

### ISSUE THREAD

**Issue by ivanhuay** [ramiel/mongoose-sequence#22]
I am trying to replace the _id of a collection and use it as a reference in another schema. But I could not make a populate since the second collection. It's possible?

**Comment by ramiel** [comment]
You mean that you're trying to use _id as a sequence and then you try to populate from another collection?

**Comment by ramiel** [comment]
Can you please post the two schema definition?

**Comment by ivanhuay** [comment]
my error, works perfectly

Thank you
