### ISSUE TITLE
Parallel or Sequential Behavior Should be Optional

### ISSUE THREAD

**Issue by KayvanMazaheri** [ramiel/mongoose-sequence#24]
When trying to access the sequence number generated by this plugin in the next middleware (another plugin or pre-save hook) you may encounter an invalid value because of this middleware registering as a   parallel hook. (See [here](https://github.com/ramiel/mongoose-sequence/blob/a00348256b5ad9c41a70f6f08bf650a5a89d9ac0/lib/sequence.js#L183))  

I suggest to add an additional configuration variable to change this behavior when the user wants this plugin to act sequential.

**Comment by KayvanMazaheri** [comment]
I'll be happy to create a PR if you confirm this.

**Comment by ramiel** [comment]
I was wondering if we need it to be parallel at all. In any case, this makes sense and I'll be happy to receive a PR 😄 . Please create it on top of `develop` branch.
