### ISSUE TITLE
Does it work atomically in cluster?

### ISSUE THREAD

**Issue by mickeyjohn** [ramiel/mongoose-sequence#26]
Hi, 
I wonder whether if any one tested in cluster? will the configured id field value, says number, still atomically unique? 

Thanks alot.

**Comment by ramiel** [comment]
Hello @mickeyjohn. I never tested it in a cluster so I can't help you. As far as an upsert works in a cluster, this should work too, but it's just a supposition

**Comment by ramiel** [comment]
I close this due to inactivity
