### ISSUE TITLE
Same field name in different schemes

### ISSUE THREAD

**Issue by yamifr07** [ramiel/mongoose-sequence#27]
Hello, I'd like to add the same field (internalCode) in two different schemes, but it throws "Counter already defined for field "internalCode"". How could I resolve it? I really need the same name.

**Comment by ramiel** [comment]
You can have the same name for two fields, but specify a different `id` for the counter.

```js
FirstSchema = mongoose.Schema({
    ...
    internalCode: Number
});
FirstSchema.plugin(AutoIncrement, {id:'firstSchemaInternalCodeCounter', inc_field: 'internalCode'});

SecondShema = mongoose.Schema({
    ...
    internalCode: Number
});
SecondShema.plugin(AutoIncrement, {id:'secondSchemaInternalCodeCounter', inc_field: 'internalCode'});
```

**Comment by ramiel** [comment]
Did it solve your problem?

**Comment by mignonnesaurus** [comment]
Hi @ramiel ! 
Thank you, I had this same issue and it worked for me! ☀️

**Comment by ramiel** [comment]
Glad to hear. I close this issue now

**Comment by jdriesen** [comment]
Hi,

I encountered the same problem, and also for me, this solution worked.
Just as an idea... maybe you should update the docu a little bit ...
Some like ... 
```
UserSchema.plugin(AutoIncrement, { id: '<unique_name_for_this_schema_counter>', inc_field: 'ID' });
```

Great Plugin BTW... Thanks for sharing your knowledge 8

Kind regards,
Johnny Driesen
Belgium

**Comment by ramiel** [comment]
Good suggestion @jdriesen. I will, for sure. In a future version id will be mandatory and this problem will go away

**Comment by dandv** [comment]
I also ran into this problem. Any plans to make `id` mandatory?

**Comment by ramiel** [comment]
Actually yes. Any PR welcome :)
