### ISSUE TITLE
Migrate from sql

### ISSUE THREAD

**Issue by yamifr07** [ramiel/mongoose-sequence#28]
I'm migrating an sql database so I need to keep old ids and then my new system will user auto increment starting from the last id.

I can't find a way to do this.

**Comment by ramiel** [comment]
Hi, I think the quickest is to create the schemas and the inserting a document. This will create a collection for the counter. Modify the value of the counter in the collection to match your latest id in mysql.

Maybe once you know how the  counter collections are made,you can create them during your import process. Let me know.

**Comment by yamifr07** [comment]
Hello. For example if id 1 and 4 were deleted, I should start from 2 and skip 4. How can I do this?

**Comment by ramiel** [comment]
In mysql, if id 4 was ever registered on the DB the next one will be 5, while 2 is not possible anymore. Btw, you cannot do this with this plugin, I'm sorry. By the way, probably I'm not really understanding your problem.

**Comment by yamifr07** [comment]
I must keep current mysql IDs. I don't know how to tell the plugin which is the last used id

**Comment by ramiel** [comment]
For an id the plugin looks for the latest sequence number stored in the counter collection for that id. If you can set that sequence number to be the latest id you have on sql, you should have done the trick
