### ISSUE TITLE
AutoIncrement is not defined

### ISSUE THREAD

**Issue by iagowp** [ramiel/mongoose-sequence#3]
Hey, I just tried to  install this on my project, but I'm getting this error
ReferenceError: AutoIncrement is not defined

I only added this line of code after adding it to the project.
UserSchema.plugin(AutoIncrement, {inc_field: 'id'});

Is there something else that needs to be done that isn't mentioned?

**Comment by ramiel** [comment]
Did you required the module?
```js
var AutoIncrement = require('mongoose-autoincrement');
UserSchema.plugin(AutoIncrement, {inc_field: 'id'});
```

**Comment by iagowp** [comment]
Nop, my bad. Thanks for the help
By the way, its 
require('mongoose-sequence')
And maybe it would be a good idea putting this on the readme, to help some dummies like me =)

**Comment by ramiel** [comment]
:+1:
