### ISSUE TITLE
Why it is renaming current collection name?

### ISSUE THREAD

**Issue by pankajinnodel** [ramiel/mongoose-sequence#30]
```
const mongoose = require('mongoose');
const AutoIncrement = require('mongoose-sequence')(mongoose);

const FormSchema = new mongoose.Schema({
    _id: {
        type: Number
    },
    Name: String,
    Description: String
}, {
    _id: false
}, {
    collection: 'Forms'
})

FormSchema.plugin(AutoIncrement, {
    inc_field: '_id'
});
module.exports = exports = mongoose.model('Form', FormSchema)
```

As you see collection name is 'Forms' but it creates collection as 'forms'.
Another issue is how to use it with existing Forms collection.Right now its creating new collection as 'forms'.

**Comment by ramiel** [comment]
This plugin does not create the collection for your schema, unless there is a bug. I'll check this.

**Comment by ramiel** [comment]
So, without the plugin the collection is correctly named "Forms"?

**Comment by pankajinnodel** [comment]
Yes collections name is 'Forms'.

**Comment by raphaelsoul** [comment]
similiar odd things
I define `crash_hashes` as collection name in the model, and insert 10 docs.
Weired thing is the collection create is `crashhashes`

And, the collection named `counters` is empty and no auto increment id in crashhashes

**Comment by ramiel** [comment]
Close due to inactivity
