### ISSUE TITLE
Two collections in one db use the same 'inc_field' conflict

### ISSUE THREAD

**Issue by xiaochutian** [ramiel/mongoose-sequence#31]
Can the plugin add collection name to the key of 'inc_field'? Something like namespace.
So that, different collections in one db can use the same 'inc_field', such as '_id'.

**Comment by ramiel** [comment]
If, in different schema, you specify the same sequence id, it should work.

```js
UserSchema.plugin(AutoIncrement, {id:'counter', inc_field: 'count'});

EmployrSchema.plugin(AutoIncrement, {id:'counter', inc_field: 'count_or_another_field'});
```

can you try and tell me if there's anything wrong?

**Comment by ramiel** [comment]
Close due to inactivity
