### ISSUE TITLE
Custom id field index

### ISSUE THREAD

**Issue by yamifr07** [ramiel/mongoose-sequence#33]
I want to make my auto increment field (not called _id) to be an index. How can I create the index?

**Comment by ramiel** [comment]
This has nothing to do with the plugin, you can use regular schema definition. i.e. if you have a field called `count` which is autoincrement you can do like this

```js
UserSchema = mongoose.Schema({
    name: String,
    count: {type: Number, index: true},
});

UserSchema.plugin(AutoIncrement, {id:'user_counter', inc_field: 'count'});
```

As you can see you can use regular mongoose properties to set the field as an index. Whenever you need to pass additional properties to the field, like in this case for the index or, let's say, for custom validation, you must define it and the type **must** be `Number`

**Comment by ramiel** [comment]
The plugin adds it unless you've already added it. In your case you want to have a more fined control over it,so add it by yourself

**Comment by yamifr07** [comment]
thank you. one more question. I want to have a required field. I tried to set required: true but because the plugin sets the value in a pre save hook, it says "Path `internalCode` is required". Is there any way to force this field to be required?

**Comment by ramiel** [comment]
No there is no way but this is an issue with mongoose itself. At the end you're code is setting the field before sending it to mongodb,so the 'required' requirement is fulfilled. I don't know what to say except to not set it as required. Why do you want to set it as required BTW?

**Comment by yamifr07** [comment]
To ensure a non empty field in the schema.

**Comment by ramiel** [comment]
I will came with something for this. For the moment I close this issue since the main problem is solved.
