### ISSUE TITLE
use same counter (shared counter) for multiple schemas

### ISSUE THREAD

**Issue by jpolvora** [ramiel/mongoose-sequence#36]
Suppose I have 2 schemas:

    let sch1 = new Schema({
        _id: Number
    })

    let  sch2 = new Schema({
        _id: Number
    })

I need to use same counter (same sequence) for both schemas

So, I expected to write the following code:

    sch1.Plugin(AutoIncrement, {id: 'mySharedCounter'})
    sch2.Plugin(AutoIncrement, {id: 'mySharedCounter'})

But the program crashes with the following error

    Counter already defined for field "mySharedCounter"
    at Sequence.getInstance (D:\PROJECTS\golden\node_modules\mongoose-sequence\lib\sequence.js:69:15)
    at Schema.plugin (D:\PROJECTS\golden\node_modules\mongoose\lib\schema.js:1198:3)

Not sure but I believe that the behavior should be: "If the counter already exists, use that counter". Or maybe create a new option (perhaps ```` useSharedCounter: true //default false ````
So the library not throw error if there's already a counter with same name if useSharedCounter=true

Then I write the following code:

    sch1.Plugin(AutoIncrement, {id: 'mySharedCounter', useSharedCounter: true})
    sch2.Plugin(AutoIncrement, {id: 'mySharedCounter', useSharedCounter: true})

**Comment by jpolvora** [comment]
I have forked this repository and I'm doing changes on my own. If anyone is interested, I can create and send a pull request for approval.

**Comment by jpolvora** [comment]
#37

**Comment by ramiel** [comment]
This is available in version 5.3.0
