### ISSUE TITLE
Counter reset how to

### ISSUE THREAD

**Issue by rernens** [ramiel/mongoose-sequence#43]
@ramiel 

hi,

I am using you plugin and I am delighted on the way it works and solve my requirements so far.

I have  the following use of your plugin

```
const AutoIncrement = autoincrement(mongoose);

EmployeeSchema.plugin( AutoIncrement, { id: 'employees_counter', inc_field: 'sequence', reference_fields: ['customer', 'establishment'] } );

export const Employee: Model<IEmployeeModel> = model<IEmployeeModel>("Employee", EmployeeSchema);
```

This works fine and keeps separate counters for employee per company/establishment.

Now I have the need to reset some scoped counters when a user deletes all the documents that are in the scope  ( ie the HR manager wants to rebuild its employees list from scratch ) and so I am trying to implement the resetCounter static method.

None of my tentative have been successful so far as the method   is never found anywhere.

In your documentation you say Model.counterReset( id, reference, callback);

Looking into your code, I am assuming that the model you are referring to is in my case Employee as 

```
this._schema.static('counterReset', function(id, reference, callback) {
        var sequence = sequenceArchive.getSequence(id);
        sequence._resetCounter(id, reference, callback);
    }.bind(this));
```

but when I try to execute Employee.counterReset ( 'employees_counter', { customer: 'xxx', establishment: 'yyy' }, errorHandler( err) )

I get an error saying that the method counterReset does not exists ...

What am I doing wrong ?

Thanks for your help

**Comment by ramiel** [comment]
Can you please share your version of mongoose and also the way you're requiring this plugin. Are you doing as is written in documentation and so do you pass your mongoose instance?

```js
const mongoose = require('mongoose')
const AutoIncrement = require('mongoose-sequence')(mongoose);
```

**Comment by ramiel** [comment]
Can you post the code where you define the schema and add the plugin to it?

**Comment by ramiel** [comment]
Sorry, I'm reading now better the code you posted and it looks fine

**Comment by ramiel** [comment]
Can you share a minimal complete code that reproduce the issue? It's hard otherwise

**Comment by rernens** [comment]
@ramiel 

Code is developed with typescript.

I am using version 4.0.1 of your plugin

below the full dependencies of my restful api

```
"dependencies": {
    "@types/express": "^4.16.0",
    "@types/mongoose": "^5.2.22",
    "body-parser": "^1.18.3",
    "cors": "^2.8.5",
    "errors": "^0.3.0",
    "express": "^4.16.4",
    "express-jwt": "^5.3.1",
    "jsonwebtoken": "^8.4.0",
    "mongoose": "^5.3.14",
    "mongoose-autopopulate": "^0.9.1",
    "mongoose-lean-virtuals": "^0.3.4",
    "mongoose-sequence": "^4.0.1",
    "nodemon": "^1.18.5",
    "ovh": "^2.0.2",
    "sendmail": "^1.4.1"
  },
```

below the complete schema written in typescript, stored in  ./schemas/employee.schema;

```
import { Document, Schema, Model, model} from "mongoose";
import { EmailSchema } from "./email.schema";
import { PhoneSchema } from "./phone.schema";
import { AddressSchema } from "./address.schema";
import { IEmployee } from "../interfaces/employee";
import * as autoincrement from "mongoose-sequence";
import * as mongoose from "mongoose";
import { HistorySchema } from "./history.schema";

export interface IEmployeeModel extends IEmployee, Document {
}

export const EmployeeSchema: Schema = new Schema({
    sequence: Number,
    customer: String,
    establishment: String,
    nir: String,
    quality: String,
    firstName: String,
    lastName: String,
    birthCountry: String,
    birthCity: String,
    birthDate: Date,
    startDate: Date,
    exitDate: Date,
    contract: String,
    duration: String,
    ratio: Number,
    category: String,
    replacing: String,
    address: AddressSchema,
    emails: [EmailSchema],
    phones: [PhoneSchema],
    idcc: String,
    citizenship: String,
    position: String,
    hiringAllowance: Date,
    firingAllowance: Date,
    permitType: String,
    permitNumber: String,
    permitExpires: String,
    provideBy: String,
    guardian: String,
    history: [HistorySchema]
}, { timestamps: true });

const AutoIncrement = autoincrement(mongoose);

EmployeeSchema.plugin( AutoIncrement, { id: 'employees_counter', inc_field: 'sequence', reference_fields: ['customer', 'establishment'] } );

export const Employee: Model<IEmployeeModel> = model<IEmployeeModel>("Employee", EmployeeSchema);
```

Creation of the counters works just fine

```
{ "_id":"5c556e9a888a93472a5d5f5b",
   "id":"employees_counter",
   "reference_value":  ["\"5c5498941f17864d225d18d4\"","\"85520050700306\""],
   "seq":58
}
```

here below the extract of the rest api that I use to reset the counter

Employee is imported as follow :  

import { Employee } from "./schemas/employee.schema";

```
router
            .route('/counters')
            .post( checkIfAuthenticated, (req: express.Request, res: express.Response, next: express.NextFunction) => {

                const action = req.body.action;
                const counter = req.body.counter;
                const reference = req.body.scope;

                if (action === 'RESET') {

                    console.log( Employee );
// TODO fix the issue : where is the reset method
                       Employee.counterReset( counter, reference, ( err ) => {
                           if ( err ) {
                               return next(err);
                           }
                           else {
                               res.status(200).json( "SUCCESS#0000")
                           }
                       });
//
                }
                else {
                    res.status(200).json( {
                        code: "ERROR#9000"
                    })
                }

            });
```

Employee points to

`export const Employee: Model<IEmployeeModel> = model<IEmployeeModel>("Employee", EmployeeSchema);`

the error thrown by the compiler is 

```
 error TS2339: Property 'counterReset' does not exist on type 'Model<IEmployeeModel, {}>'.

429                     Employee.counterReset( counter, reference, ( err ) => {
```

I just found out that replacing

 Employee.counterReset( counter, reference, ( err ) => ....

by 

Employee.schema.statics.counterReset( counter, reference, ( err ) => ...

fixes the issue.

writing it 

 Employee['counterReset']( counter, reference, ( err ) => ....

also works

**Comment by ramiel** [comment]
Oh but it's not a runtime error,it's a compiler error! So yes you have to tell typescript that that property exists even if it cannot find it. The property is set by mongoose and it creates the appropriate getter to use it but it's not on the object prototype. If you tell the compiler to ignore that issue, you'll see that your code will work. I'm not very experienced with typescript so I don't know how to tell it that the model class has that property. Do not use your first workround because it relies on the way mongoose save the reference to the function that can change.

**Comment by rernens** [comment]
@ramiel 

Hi Fabrizzio,

I also had a runtime error until I switched to the above notation.

`Employee['counterReset']( counter, reference, ( err ) => ....`

Further research brought me to the final solution which can be of use for others.

To use your static method, one needs to extend its own model definition with you method in the following manner :

```
export interface IEmployeeDocument extends IEmployee, Document {
  add any method but no statics here
}

export interface IEmployeeModel extends Model<IEmployeeDocument> {
    counterReset( id: string, reference: any, callback: any ): void;
}
```

then you can use

`Employee.counterReset( counter, reference, ( err ) => ....`

Thanks for your help.

**Comment by ramiel** [comment]
Ok, it seems to me that typescript is adding complexity here. Thank you for sharing with the others your solution!

**Comment by rernens** [comment]
@ramiel

you are right but at the same time, strong typing avoids many issues at runtime. I am  a fan.

**Comment by ramiel** [comment]
I totally agree. It was just a comment on the specific situation. It's worth to overcome it.
