### ISSUE TITLE
reset counter on _id field

### ISSUE THREAD

**Issue by siyuan-li** [ramiel/mongoose-sequence#50]
Hello I set the counter on _id filed following the REAME

```javascript
UserSchema = mongoose.Schema({
    _id: Number,
    name: String
}, { _id: false });
UserSchema.plugin(AutoIncrement);
```

And reset _id as follow

```javascript
Model.counterReset('counter_id', function(err) {
    // Now the counter is 0
});
```
However, then I delete all documents in database and save new document, the _id filed is not 
reset to 0.

**Comment by ramiel** [comment]
What happens before you delete the documents? The _id counter is 0 or not?

**Comment by siyuan-li** [comment]
It is my fault. After the investigation, I found that I didn't reset the counter at the correct place in my code. @ramiel Thank you very much for your help! Sorry to open this issue.

**Comment by ramiel** [comment]
No problem. Happy to know your problem is gone!
