### ISSUE TITLE
Ever tested on AWS Elastic Beanstalk ?

### ISSUE THREAD

**Issue by jdriesen** [ramiel/mongoose-sequence#55]
Hi,

I wrote a very simple Node Express Mongoose Application (just one model)
Everything works fine on my local machine.

Though, as soon as I deploy to AWS Elastic Beanstalk, the App doesn't work ...

When I comment the lines 
```
const AutoIncrement = require('mongoose-sequence')(mongoose);
```
and
```
userSchema.plugin(AutoIncrement, {
  id: 'userAutoInc',
  inc_field: 'ID'
});
```
and I re-deploy, my App works fine again (though, of course;  without an Autnumber field.

So, after half a day "debugging by elimination", I think I can conclude your module is giving a small problem on AWS...

Health of the server changes to DEGRADED, which results in a 502 error ... (i.e. application is not running on the server, due to the fact the compilation failed...)

 I'm using a MongoDB on Atlas...

I THINK (though, I might be wrong), that for one reason or another, your module isn't able to create the collection "counters" ... (but once again, that's just a wild guess)

Any help would be more than welcome, cause we really LIKE your module !!
And I'm certainly willing to do some tests for you.

Thanks in advance for your reply,

Johnny Driesen
Belgium

**Comment by ramiel** [comment]
Hello @jdriesen . 
So, I don't really now Beanstalk so you have to help me debugging your application. Is there any error shown somewhere? The 502 error is indeed the most front error you can get, but what is causing that? Is there a place where you can look at? Maybe some log somewhere? Usually you can integrate any AWS solution with Amazon CloudWatch, can you try?

If not, and if the problem may be the impossibility to create the counter collection, can you try to create it before running the script?

Help me to help you :)

**Comment by ramiel** [comment]
I clos this since no new details since long time.
