### ISSUE TITLE
Wont work with .insertMany

### ISSUE THREAD

**Issue by nlug** [ramiel/mongoose-sequence#7]
Like title, it wont work with .insertMany
Can you check it out?

**Comment by ramiel** [comment]
I'll check out soon. Thank you for noticing this

**Comment by ramiel** [comment]
Looks like the hooks called during insertMany are not useful to increment the counter (you can look Automattic/mongoose#3846). I'll look if there is another way to achieve this.

**Comment by ramiel** [comment]
Meanwhile I added a test for this feature the you can find in this [commit](https://github.com/ramiel/mongoose-sequence/commit/07e4de2ba2d6a927ae06e2c3651192f51448140e)

**Comment by ramiel** [comment]
Another reference [here](https://github.com/Automattic/mongoose/issues/723#issuecomment-178866230).
Following the discussion I believe you can use `.create` instead. It's slower than insertMany but calls the hook. The order is not garantueed to be the same as the documents definition, as explained at Automattic/mongoose#4038. 
So if you have not a lot of insertions, or performance requirements, and the order can be not guaranteed, I suggest you to use .create. Let me know.

**Comment by nlug** [comment]
It's a nice solution. Thank you for checking it out.
Have a nice day!
