### ISSUE TITLE
Problem with more then one collections attache AutoIncrement!

### ISSUE THREAD

**Issue by thearabbit** [ramiel/mongoose-sequence#73]
I have the problem with more than one collections attach
```js
EmployeesSchema.plugin(AutoIncrement, { inc_field: 'id' })
----------
CustomerSchema.plugin(AutoIncrement, { inc_field: 'id' })
```

**Comment by ramiel** [comment]
Please, try to use `id` when defining the autoincrement, something like

```js
EmployeesSchema.plugin(AutoIncrement, { id: 'employCounter', inc_field: 'id' });
CustomerSchema.plugin(AutoIncrement, { id: 'customerCounter', inc_field: 'id' });
```

If this doesn't solve the problem, can you share about what the problem is?

**Comment by thearabbit** [comment]
Thanks very quick reply.
I will try soon, and feedback

**Comment by thearabbit** [comment]
Very thanks it work fine.
I will try to check doc for detail.
