### ISSUE TITLE
_id is incremented, and my inc_field value is ignored

### ISSUE THREAD

**Issue by NickHodges** [ramiel/mongoose-sequence#74]
First, I'm using Typescript.

In my App class for an Express/Mongoose app, I have:

```
   private mongoose = require('mongoose');
   private autoIncrement = require('mongoose-sequence')(mongoose);
```

Then, in my constructor I have:

```
  constructor() {
    this.app = express();
    this.config();
    this.routePrv.routes(this.app);
    this.mongoSetup();

    mongoose.model('Todos', TodoSchema);

    TodoSchema.plugin(this.autoIncrement, {
      inc_field: 'todoid',
      start_seq: 422
    });
  }
```

This compiles and "works" in that the alpha-numeric `_id` field from mongoose is auto-incremented when posting via a REST API in Postman.

My `todoid` field doesn't exist in the resulting JSON and is completely ignored.

How do I get my  `todoid` field to auto-increment and appear in the resulting record?

I hope this is okay to ask here.

**Comment by ramiel** [comment]
Hello @NickHodges, yes is ok to ask here. Can you post your schema please? 

From your code, what is `this.autoIncrement`? Why isn't it just `autoIncrement`?

**Comment by NickHodges** [comment]
Thanks for answering.

First -- it's `this.autoincrement` because I'm using TypeScript. ;-)

My schema is as follows:

```
//   /lib/models/crmModel.ts

import * as mongoose from 'mongoose';

export const TodoSchema: mongoose.Schema = new mongoose.Schema({
  todoid: {
    type: Number
  },
  title: {
    type: String,
    required: 'Enter a title'
  },
  note: {
    type: String
  },
  complete: {
    type: Boolean,
    default: false
  },
  editMode: {
    type: Boolean,
    default: false
  }
});
```

Thanks for your interest and assistance.

**Comment by ramiel** [comment]
Oh, I see, you define `mongoose` and `autoIncrement` as private property of your class. But then you're using:

```js
 mongoose.model('Todos', TodoSchema);
```

and not `this.mongoose`. Please, be sure that the mongoose instance you use to connect is the same you pass to the plugin when requiring it or the plugin won't work.

As a side note, and totally my personal opinion you can ignore happily: having some requirement as private property of your class seems a bit ackward because the imports should be unique and not bound to an object instance. I can't see all the code so sorry if this comment is not appropriate.

Anyway, if for any reason there are more than one mongoose instance, the code won't work

**Comment by chrisp986** [comment]
Hello,
i have the same issue with my implementation. I have tried to implement the scoped counter and also just the global sequence. Both times there is no new id field created and the _id is incremented.


```
itemSchema = mongoose.Schema({
	title: String,
	description: String,
	createdBy: String,
	msco: String,
	customerName: String,
	projectNumber: Number,
	createdDate: String,
	lastUpdate: String,
	status: { type: String, default: 'New' },
	responsible: { type: String, default: 'Not defined' },
	affectedSystem: { type: String, default: 'Not defined' },
	itemId: Number,
	id: Number,
});

const Item = new mongoose.model('Item', itemSchema);

itemSchema.plugin(AutoIncrement, {
	id: 'requestNumber',
	inc_field: 'itemId',
	reference_fields: [ 'projectNumber' ],
});
```

My idea was to increment itemId based on the projectNumber.

Thanks in advance.

**Comment by ramiel** [comment]
Can I see how you require mongoose and the plugin?

**Comment by chrisp986** [comment]
Yes, sure.

```
const mongoose = require('mongoose');
const AutoIncrement = require('mongoose-sequence')(mongoose);
```

I just copied it from the readme.

**Comment by NickHodges** [comment]
OKay -- so here's what I've done -- I took your advice and did this:

https://github.com/NickHodges/todonode/blob/master/lib/app.ts

I've required stuff in a global way.

Alas, it is still not working.  I can't get the `todoid` field to be auto-populated,

Thank you very much for taking a look.

**Comment by ramiel** [comment]
ok, I'll check when I can.

**Comment by NickHodges** [comment]
Thank you very much. I'm grateful for your assistance.

**Comment by ramiel** [comment]
The problem in your code is that your adding the plugin to a schema after you create a model from it. 
This is a problem with the way mongoose works, not related to this plugin.
I removed the plugin usage from app.ts and changed the file `models/crmModels.ts` to be:

```ts
//   /lib/models/crmModel.ts
import mongoose from 'mongoose';
const autoIncrement = require('mongoose-sequence')(mongoose);

const TodoSchema: mongoose.Schema = new mongoose.Schema({
  todoid: {
    type: Number
  },
  title: {
    type: String,
    required: 'Enter a title'
  },
  note: {
    type: String
  },
  complete: {
    type: Boolean,
    default: false
  },
  editMode: {
    type: Boolean,
    default: false
  }
});


TodoSchema.plugin(autoIncrement, {
  inc_field: 'todoid',
  start_seq: 422
});


export {TodoSchema};
```
and it works, two calls to the post route creates these entries on DB:

![Screenshot_20190919_161603](https://user-images.githubusercontent.com/324687/65252205-d7df7000-daf8-11e9-8e41-2dc15861b1f4.png)

In general you should expose models, not schema. I see you create a model from the same schema several times in your application but this is not really correct: you should create your model once and use it across your application, not recreating it everytime you need it. Actually mongoose should have an internal cache mechanism but it's not exposed and you should not rely on it.

**Comment by NickHodges** [comment]
@ramiel  -- Thank you so much!  This works like a champ.  I'm very appreciative of your time and expertise.

**Comment by chrisp986** [comment]
@ramiel -- Yes, it is also working for me now, thank you very much for your help!

**Comment by ramiel** [comment]
Ok @NickHodges and @chrisp986, glad of being helpful. Good luck
