### ISSUE TITLE
Using a nested field as inc_field

### ISSUE THREAD

**Issue by ManoelLobo** [ramiel/mongoose-sequence#75]
Is it possible to use a nested field as `inc_field`?

Considering a Schema like
```
const Schema = new mongoose.Schema({
  prop1: {type: Number},
  // ...
  propN: {
    date: {type: Date},
    fieldToInc: {type: Number}
  }
})
```

how would I implement the sequence to `propN.fieldToInc`?

Something like
```
Schema.plugin(Sequence, {
  id: 'nested_seq',
  inc_field: 'propN.fieldToInc' // not working, just an example
  // ...
})
```

By the way, thank you very much for this awesome library!

**Comment by ramiel** [comment]
Hello @ManoelLobo, thank you. This is not possible at them moment, neither I ever thought to include this functionality which seems very useful altough. I guess this should be added and any PR is welcome!
