### ISSUE TITLE
How to reset _Id field? 

### ISSUE THREAD

**Issue by AmosSpark** [ramiel/mongoose-sequence#87]
Hi, I'm not using a counter, but incrementing _Id field. I'm happy with the result except that the _Id don't get to reset after deleting a document.  

Example: doc2 should reset to _Id: 1 after doc1 which was _id: 1 have been deleted. But no,  doc2 still maintained _id:2. 

How do I do that? 
@ramiel

**Comment by ramiel** [comment]
Hello @AmosSpark. This has already been discussed in #79 and the short answer is that this is not possible. Read the comments to the other issue for more details
