### ISSUE TITLE
Errors initializing within NestJS

### ISSUE THREAD

**Issue by toddbruner** [ramiel/mongoose-sequence#90]
I'm trying to use mongoose-sequence from within a NestJS application.  Full reproducible code at https://github.com/toddbruner/s4n3.  I've tried several different invocation methods and unfortunately have been unable to find a way that works.  (Problem described in more detail on  https://stackoverflow.com/questions/63020177/nestjs-and-mongoose-using-mongoose-sequence). 

Essentially, trying to initialize the plugin I either get a RangeError: Maximum call stack size exceeded, or a failure to connect to the database.

Do you have any ideas on what I'm doing wrong here?  Thanks.

**Comment by ramiel** [comment]
I don't really know NestJS, but I posted a possible solution on [StackOverflow](https://stackoverflow.com/questions/63020177/nestjs-and-mongoose-using-mongoose-sequence/63087578#63087578)

**Comment by ramiel** [comment]
Also, you're trying to add the plugin to the connection

```js
const AutoIncrement = AutoIncrementFactory(connection);
connection.plugin(AutoIncrement, {inc_field: 'id'});
```

but it must be attached to a schema, not the connection

**Comment by toddbruner** [comment]
Yes, but that's how the NestJS documentation states you add a plugin for use with all schemas through their mongoose wrapper:  https://docs.nestjs.com/techniques/mongodb#plugins

I've asked them, but they don't know what's going on either.  The attempts you reference on the stackoverflow answer are a result of their suggestions.  

Thank you for your help.

**Comment by ramiel** [comment]
In the documentation you pointed they actually register the plugin for one schema only

```js
@Module({
  imports: [
    MongooseModule.forFeatureAsync([
      {
        name: Cat.name,
        useFactory: () => {
          const schema = CatsSchema;
          schema.plugin(require('mongoose-autopopulate'));
          return schema;
        },
      },
    ]),
  ],
})
export class AppModule {}
```

**Comment by toddbruner** [comment]
Right below that example, they show an example for applying a plugin for all schemas:

> To register a plugin for all schemas at once, call the .plugin() method of the Connection object. You should access the connection before models are created; to do this, use the connectionFactory:

i```
mport { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';

@Module({
  imports: [
    MongooseModule.forRoot('mongodb://localhost/test', {
      connectionFactory: (connection) => {
        connection.plugin(require('mongoose-autopopulate'));
        return connection;
      }
    }),
  ],
})
export class AppModule {}
```

**Comment by ramiel** [comment]
I understand. I still believe your problem is the way you import the module, which seems wrong to me.

Instead of this

```js
import AutoIncrementFactory = require('mongoose-sequence');
```

you should use this

```js
const AutoIncrementFactory = require('mongoose-sequence');
```

**Comment by artem-itdim** [comment]
For feature you can do this

```javascript
@Module({
  imports: [
    MongooseModule.forFeatureAsync([
      {
        name: Cat.name,
        useFactory: (connection: Connection) => {
          const AutoIncrementFactory = require('mongoose-sequence');
          const AutoIncrement = AutoIncrementFactory(connection);

          const schema = CatsSchema;
          schema.plugin(AutoIncrement, {
            inc_field: 'seqID',
            start_seq: 0
          });

          return schema;
        },
        inject: [getConnectionToken()]
      },
    ]),
  ],
})
export class AppModule {}
```

**Comment by fromage9747** [comment]
@artem-itdim 

I have configured my model as yours but the field that I want to auto-increment I have made required.  Due to this, I am getting a validation error from mongoose saying that I have not provided a value for the field.

I assumed that this module would handle the generate of that field? 

It there something that I am missing?

**Comment by fromage9747** [comment]
@artem-itdim Nevermind.  It was due to having the field as required.  Found this on another thread https://stackoverflow.com/questions/15508912/mongoose-auto-increment

Everything is working now!

**Comment by brandart** [comment]
@fromage9747 where were your required field? I can't fix it.

**Comment by fromage9747** [comment]
> @fromage9747 where were your required field? I can't fix it.

When you initialize the module in your app.module.ts.

For example, this is mine, working:

`
MongooseModule.forFeatureAsync([

      {
        name: InvoiceModel.name,
        useFactory: async (connection: Connection) => {
          const schema = InvoiceSchema;
          const AutoIncrement = AutoIncrementFactory(connection);
          schema.plugin(AutoIncrement, { 
            id: 'invoice_seq',
            inc_field: 'invoice_number', 
            start_seq: 1 
          });
          return schema;
        },
        inject: [getConnectionToken()],
      },
    ]),`

I do not make the field required.  If its required, then it does not work and will throw an error.

**Comment by brandart** [comment]
so `invoice_number` is your variable in your schema, right?
and what is your `invoice_seq`?

can you add your `MongooseModule.forRootAsync()` call pls? :)

**Comment by fromage9747** [comment]
invoice_number is the key in the document in the invoices collection, invoice_seq is what is created in the counters collection which is automatically created in order for the last increment to be kept track of.

`
@Module({
  imports: [
    ConfigModule.forRoot(),
    UsersModule, 
    MongooseModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => ({
        uri: configService.get('DATABASE_URL'),
        'useCreateIndex': true,
        'useNewUrlParser': true,
        'useFindAndModify': false,
        'useUnifiedTopology': true
      }),
      inject: [ConfigService],
    }),
    MongooseModule.forFeatureAsync([
      {
        name: InvoiceModel.name,
        useFactory: async (connection: Connection) => {
          const schema = InvoiceSchema;
          const AutoIncrement = AutoIncrementFactory(connection);
          schema.plugin(AutoIncrement, { 
            id: 'invoice_seq',
            inc_field: 'invoice_number', 
            start_seq: 1 
          });
          return schema;
        },
        inject: [getConnectionToken()],
      },
    ]),
    MailerModule.forRootAsync({
      useFactory: () => ({
        transport: {
          host: process.env.SMTP_SERVER,
          port: process.env.SMTP_PORT,
          secure: process.env.SECURE_CONNECTION, // upgrade later with STARTTLS
          auth: {
            user: process.env.SMTP_USERNAME,
            pass: process.env.SMTP_PASSWORD,
            },
            tls: {
              ciphers: process.env.TLS_CIPHERS
            }
        },
        defaults: {
          from: process.env.SMTP_FROM,
        },
        template: {
          dir: process.cwd() + '/templates/',
          adapter: new HandlebarsAdapter(),
          options: {
            strict: true,
          },
        },
      }),
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})

`

No matter what I do, I can't get github to format it nicely.

**Comment by brandart** [comment]
I got it running now but I it doesn't add any counter to the document.

have you got a link to this repo or is it private?

**Comment by fromage9747** [comment]
It's a private repository. You also have to make sure that the "invoice_number" as I have used above also exists in the schema that you are creating for your own collection. So as I have added the "invoice_number" above when initialising the app, I also have it in my model. 

`
export const InvoiceSchema = new mongoose.Schema({
	invoice_number: {
		type: Number,
		// required: true,
		index: true
	},

`

**Comment by brandart** [comment]
doesn't change anything unfortunately... ^^ 

how are you inserting new things?

and have you something like this in your code?
`MongooseModule.forRoot('mongodb://localhost/test', {
      connectionFactory: (connection) => {
        const AutoIncrementFactory = require('mongoose-sequence');
        const AutoIncrement = AutoIncrementFactory(connection);
        connection.plugin(AutoIncrement, {inc_field: 'seq'});
        return connection;
      }
 `

**Comment by brandart** [comment]
have you imported `AutoIncrementFactory ` from anywhere?

**Comment by fromage9747** [comment]
In my invoicing service I am injecting the model, creating a new object and saving it. Not at my desk right now but I will copy and paste some excerpts when I am back

**Comment by brandart** [comment]
you are amazing, thank you!

**Comment by brandart** [comment]
alright, my problem was that I had multiple `MongooseModule.forRootAsync`

**Comment by fromage9747** [comment]
Excellent 👍 glad you found the problem

**Comment by fromage9747** [comment]
@brandart Hey man,  it would appear that I messed mine autoincrement up.  There is supposed to be another comment under counters and I went and deleted mine by accident.  Could you send me a screenshot of your counters collection?

**Comment by brandart** [comment]
a counter document looks like this:
```
{
    "id": "addressPointId",
    "reference_value": null,
    "seq": 258
}
```

**Comment by fromage9747** [comment]
Thanks man. I did have another document in there which I thought was the problem but it wasn't... I gave up and just created my own auto-increment module.

**Comment by brandart** [comment]
yeah same :D

**Comment by Karman40** [comment]
I receive this error message, but I can't resolve it.

`RangeError: Maximum call stack size exceeded`

```
    MongooseModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => ({
        uri: configService.get('mongodb.uri'),
        authSource: configService.get('mongodb.auth_db'),
        auth: {
          username: configService.get('mongodb.username'),
          password: configService.get('mongodb.password'),
        },
        connectionFactory: (connection) => {
          const AutoIncrementFactory = require('mongoose-sequence');
          const AutoIncrement = AutoIncrementFactory(connection);
          connection.plugin(AutoIncrement, { inc_field: 'seq' });
          return connection;
        }
      }),
      inject: [ConfigService]
    }),
```

Does anyone have any idea what could be wrong?
