### ISSUE TITLE
Reset the id after some testing

### ISSUE THREAD

**Issue by ahmedbana** [ramiel/mongoose-sequence#91]
Hi, 

When i made some test but now i need to reset the id counter and start from new number, When i try to do this it keeps saying that "id" is used before.
`couponSchema.plugin(AutoIncrement, {inc_field: 'id',start_seq: 2000001})`
error : 
`throw new Error(Counter already defined for field "${id}");`
Any help ?

**Comment by ramiel** [comment]
You can use the resetCounter api. Look at this: https://github.com/ramiel/mongoose-sequence#reset-a-counter

**Comment by ahmedbana** [comment]
it gave me this error : 
`Coupon.counterReset("id", function(err) {
       ^
TypeError: Coupon.counterReset is not a function`

Here is my code : 

```
const Coupon = mongoose.model("Coupon", couponSchema)
Coupon.counterReset("id", function(err) {
    console.log(err)
});
```

**Comment by ramiel** [comment]
Can you show me the `couponSchema` related code?

**Comment by ahmedbana** [comment]
```
const mongoose = require('mongoose')
const AutoIncrement = require('mongoose-sequence')(mongoose)
const couponSchema = new mongoose.Schema({
   
    
    name: {
        type: String,
        required: true
    },
    info: {
        type: String,
    },
    code:{
        type: String,
        uppercase: true,
        required: true,
        unique: true
    },
    type: { 
        type: Number,
        required: true,
        default: 0
    },
    start: {
        type: Date,
        required: true,
        default: Date.now,
    },
    end: {
        type: Date,
    },
    active: {
        type: Boolean,
        required: true,
        default: true
    },
    value: { 
        type: Number,
        required: true
    },
    max_value: { 
        type: Number,
    },
    limit: {
        type: Number,
        default: 0
    },
    limit_per_user: {
        type: Boolean,
        default: true
    },
    used: {
        type: Number,
        default: 0
    },
    users: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
    }]

}, {
    timestamps: true
})

couponSchema.methods.toJSON = function () {
    const coupon = this
    const couponObject = coupon.toObject()
    return couponObject
}

couponSchema.plugin(AutoIncrement, {inc_field: 'id',start_seq: 2000001,collection_name:"coupon_Schema" })

const Coupon = mongoose.model('Coupon', couponSchema)

module.exports = Coupon
```

**Comment by ramiel** [comment]
This is very strange. Your code look ok and it should have that method. I'll try to reproduce

**Comment by ramiel** [comment]
I tried to reproduce your issue in this repository: https://github.com/ramiel/issue91

It's working. Can you check it and try to find any difference? Or try to run it on your machine and see if it's working?

**Comment by ahmedbana** [comment]
I tried, Same error

```
Project\src\index.js:71
Coupon.counterReset("id", err => {
       ^

TypeError: Coupon.counterReset is not a function
```

**Comment by ahmedbana** [comment]
The reset worked with other Models but not for Coupons, Weird.

**Comment by ramiel** [comment]
> I tried, Same error
> 
> ```
> Project\src\index.js:71
> Coupon.counterReset("id", err => {
>        ^
> 
> TypeError: Coupon.counterReset is not a function
> ```

You mean you run the project on the repo `issue91` and it gives you that error?

**Comment by yamilelias** [comment]
@ahmedbana I had the same error too. The code you added use `module.exports = Coupon` but maybe you are using `exports.Coupon` instead. In this case, you may need to change the way you call it. Changing it to `const { Coupon } = require('./coupon');`.

This worked for me because when I tried to get the Model it wasn't the default, so I needed to destruct the object to use it. I hope this helps you. If it works for others and not for Coupon, try debugging your code, maybe it is related.
