### ISSUE TITLE
How to prefix _id / support custom string _id

### ISSUE THREAD

**Issue by dazzito** [ramiel/mongoose-sequence#95]
I would like to prefix the auto-increment _id with string, is this possible? (e.g PID-001, PID-002...)

This is for a custom _id field. The doc states that to modify the _id, it has to be explicitly specified as Number, but in mongodb _id it doesn't necessarily have to be a number.

**Comment by ramiel** [comment]
It's not possible with this library to prefix the field content.

Taking it from another perspective, why not using normal _id and delegating another filed as counter?

**Comment by ramiel** [comment]
Another solution is what suggested in #102
